FROM continuumio/miniconda3:latest

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
        mlflow==1.24.0 \
        boto3==1.21.16 \
        pymysql==1.0.2

ADD scripts/wait-for-it.sh /app/scripts/
WORKDIR /app

COPY scripts/wait-for-it.sh wait-for-it.sh 
RUN chmod +x wait-for-it.sh